-- MySQL Script generated by MySQL Workbench
-- 08/07/19 18:14:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema bd_autoscraping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_autoscraping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_autoscraping` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema ahac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ahac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ahac` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;

USE `bd_autoscraping` ;

-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_areas` (
  `cod_area_pk` INT(11) NOT NULL,
  `txt_nombre_area` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`cod_area_pk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_asignatura` (
  `cod_asignatura_pk` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cod_area_pk` INT(11) NULL DEFAULT NULL,
  `txt_nombre_asignatura` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`cod_asignatura_pk`),
  INDEX `fk_tbl_asignatura_tbl_areas1_idx` (`cod_area_pk` ASC),
  CONSTRAINT `fk_tbl_asignatura_tbl_areas1`
    FOREIGN KEY (`cod_area_pk`)
    REFERENCES `bd_autoscraping`.`tbl_areas` (`cod_area_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_docente` (
  `num_docente_pk` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_nombre` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`num_docente_pk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_carrera` (
  `cod_carrera_pk` INT NOT NULL AUTO_INCREMENT,
  `txt_nombre_carrera` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_carrera_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_estudiante` (
  `num_cuenta_pk` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cod_carrera_fk` INT NOT NULL COMMENT 'Antes era txt_carrera varchar 100',
  `txt_nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_centro_estudio` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`num_cuenta_pk`),
  INDEX `fk_tbl_estudiante_tbl_carrera1_idx` (`cod_carrera_fk` ASC),
  CONSTRAINT `fk_tbl_estudiante_tbl_carrera1`
    FOREIGN KEY (`cod_carrera_fk`)
    REFERENCES `bd_autoscraping`.`tbl_carrera` (`cod_carrera_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_periodo` (
  `num_periodo_pk` INT(11) NOT NULL,
  `num_anio_pk` INT(11) NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`num_anio_pk`, `num_periodo_pk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_seccion` (
  `num_seccion_pk` INT(11) NOT NULL AUTO_INCREMENT,
  `num_periodo_pk` INT(11) NOT NULL,
  `num_anio_pk` INT(11) NOT NULL,
  `cod_asignatura_ck` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `num_docente_ck` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `txt_HI` VARCHAR(6) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_HF` VARCHAR(6) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_aula` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `txt_edificio` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_dias` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`num_seccion_pk`, `cod_asignatura_ck`, `num_periodo_pk`, `num_anio_pk`),
  INDEX `fk_tbl_seccion_tbl_asignatura1_idx` (`cod_asignatura_ck` ASC),
  INDEX `fk_tbl_seccion_tbl_docente1_idx` (`num_docente_ck` ASC),
  INDEX `fk_tbl_seccion_tbl_periodo1_idx` (`num_anio_pk` ASC, `num_periodo_pk` ASC),
  CONSTRAINT `fk_tbl_seccion_tbl_asignatura1`
    FOREIGN KEY (`cod_asignatura_ck`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura` (`cod_asignatura_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_seccion_tbl_docente1`
    FOREIGN KEY (`num_docente_ck`)
    REFERENCES `bd_autoscraping`.`tbl_docente` (`num_docente_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_seccion_tbl_periodo1`
    FOREIGN KEY (`num_anio_pk` , `num_periodo_pk`)
    REFERENCES `bd_autoscraping`.`tbl_periodo` (`num_anio_pk` , `num_periodo_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10655
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_historial` (
  `num_cuenta_ck` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cod_asignatura_ck` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `num_seccion_pk` INT(11) NOT NULL,
  `num_periodo_pk` INT(11) NOT NULL,
  `num_anio_pk` INT(11) NOT NULL,
  `num_calificacion` INT(11) NOT NULL,
  `num_uv` INT(11) NOT NULL,
  `txt_obs` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`num_cuenta_ck`, `cod_asignatura_ck`, `num_seccion_pk`, `num_periodo_pk`, `num_anio_pk`),
  INDEX `fk_tbl_historial_tbl_estudiante1_idx` (`num_cuenta_ck` ASC),
  INDEX `fk_tbl_historial_tbl_seccion1_idx` (`num_seccion_pk` ASC, `cod_asignatura_ck` ASC, `num_periodo_pk` ASC, `num_anio_pk` ASC),
  CONSTRAINT `fk_tbl_historial_tbl_estudiante1`
    FOREIGN KEY (`num_cuenta_ck`)
    REFERENCES `bd_autoscraping`.`tbl_estudiante` (`num_cuenta_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_historial_tbl_seccion1`
    FOREIGN KEY (`num_seccion_pk` , `cod_asignatura_ck` , `num_periodo_pk` , `num_anio_pk`)
    REFERENCES `bd_autoscraping`.`tbl_seccion` (`num_seccion_pk` , `cod_asignatura_ck` , `num_periodo_pk` , `num_anio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_indice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_indice` (
  `num_cuenta_pk` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `num_periodo_pk` INT(11) NOT NULL,
  `num_anio_pk` INT(11) NOT NULL,
  `num_indice_periodo` INT(11) NOT NULL,
  `num_indice_global` INT(11) NOT NULL,
  PRIMARY KEY (`num_periodo_pk`, `num_anio_pk`, `num_cuenta_pk`),
  INDEX `fk_tbl_indice_tbl_estudiante1_idx` (`num_cuenta_pk` ASC),
  INDEX `fk_tbl_indice_tbl_periodo1_idx` (`num_anio_pk` ASC, `num_periodo_pk` ASC),
  CONSTRAINT `fk_tbl_indice_tbl_estudiante1`
    FOREIGN KEY (`num_cuenta_pk`)
    REFERENCES `bd_autoscraping`.`tbl_estudiante` (`num_cuenta_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_indice_tbl_periodo1`
    FOREIGN KEY (`num_anio_pk` , `num_periodo_pk`)
    REFERENCES `bd_autoscraping`.`tbl_periodo` (`num_anio_pk` , `num_periodo_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_tipo_usuario` (
  `cod_tipo_usuario_pk` INT(11) NOT NULL,
  `txt_tipo_usuario` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`cod_tipo_usuario_pk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_usuario` (
  `cod_usuario_pk` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_tipo_usuario_pk` INT(11) NOT NULL,
  `txt_nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `num_empleado` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `txt_contrasenia` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`cod_usuario_pk`),
  INDEX `fk_tbl_usuario_tbl_tipo_usuario1_idx` (`cod_tipo_usuario_pk` ASC),
  CONSTRAINT `fk_tbl_usuario_tbl_tipo_usuario1`
    FOREIGN KEY (`cod_tipo_usuario_pk`)
    REFERENCES `bd_autoscraping`.`tbl_tipo_usuario` (`cod_tipo_usuario_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_plan_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_plan_estudio` (
  `cod_plan_estudio_pk` INT NOT NULL AUTO_INCREMENT,
  `cod_carrera_fk` INT NOT NULL,
  PRIMARY KEY (`cod_plan_estudio_pk`),
  INDEX `fk_tbl_plan_estudio_tbl_carrera1_idx` (`cod_carrera_fk` ASC),
  CONSTRAINT `fk_tbl_plan_estudio_tbl_carrera1`
    FOREIGN KEY (`cod_carrera_fk`)
    REFERENCES `bd_autoscraping`.`tbl_carrera` (`cod_carrera_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_asignatura_x_plan_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_asignatura_x_plan_estudio` (
  `cod_asignatura_x_plan_estudio_pk` INT NOT NULL AUTO_INCREMENT,
  `cod_plan_estudio_fk` INT NOT NULL,
  `cod_asignatura_fk` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `bol_pertenece_carrera` TINYINT NULL,
  PRIMARY KEY (`cod_asignatura_x_plan_estudio_pk`),
  INDEX `fk_tbl_asignatura_x_plan_estudio_tbl_plan_estudio1_idx` (`cod_plan_estudio_fk` ASC),
  INDEX `fk_tbl_asignatura_x_plan_estudio_tbl_asignatura1_idx` (`cod_asignatura_fk` ASC),
  CONSTRAINT `fk_tbl_asignatura_x_plan_estudio_tbl_plan_estudio1`
    FOREIGN KEY (`cod_plan_estudio_fk`)
    REFERENCES `bd_autoscraping`.`tbl_plan_estudio` (`cod_plan_estudio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignatura_x_plan_estudio_tbl_asignatura1`
    FOREIGN KEY (`cod_asignatura_fk`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura` (`cod_asignatura_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_requisito_x_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_requisito_x_asignatura` (
  `cod_asignatura_x_plan_estudio_ck` INT NOT NULL,
  `cod_asignatura_x_plan_estudio_requisito_ck` INT NOT NULL,
  INDEX `fk_tbl_requisito_x_asignatura_tbl_asignatura_x_plan_estudio_idx` (`cod_asignatura_x_plan_estudio_requisito_ck` ASC),
  PRIMARY KEY (`cod_asignatura_x_plan_estudio_ck`, `cod_asignatura_x_plan_estudio_requisito_ck`),
  CONSTRAINT `fk_tbl_requisito_x_asignatura_tbl_asignatura_x_plan_estudio1`
    FOREIGN KEY (`cod_asignatura_x_plan_estudio_ck`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura_x_plan_estudio` (`cod_asignatura_x_plan_estudio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_requisito_x_asignatura_tbl_asignatura_x_plan_estudio2`
    FOREIGN KEY (`cod_asignatura_x_plan_estudio_requisito_ck`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura_x_plan_estudio` (`cod_asignatura_x_plan_estudio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_forma_03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_forma_03` (
  `num_cuenta_ck` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `num_anio_ck` INT(11) NOT NULL,
  `num_periodo_ck` INT(11) NOT NULL,
  `cod_asignatura_x_plan_estudio_ck` INT NOT NULL,
  `bol_prediccion_aprueba` TINYINT NULL,
  PRIMARY KEY (`num_anio_ck`, `num_periodo_ck`, `cod_asignatura_x_plan_estudio_ck`, `num_cuenta_ck`),
  INDEX `fk_tbl_forma_03_tbl_asignatura_x_plan_estudio1_idx` (`cod_asignatura_x_plan_estudio_ck` ASC),
  INDEX `fk_tbl_forma_03_tbl_periodo1_idx` (`num_anio_ck` ASC, `num_periodo_ck` ASC),
  INDEX `fk_tbl_forma_03_tbl_estudiante1_idx` (`num_cuenta_ck` ASC),
  CONSTRAINT `fk_tbl_forma_03_tbl_asignatura_x_plan_estudio1`
    FOREIGN KEY (`cod_asignatura_x_plan_estudio_ck`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura_x_plan_estudio` (`cod_asignatura_x_plan_estudio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_forma_03_tbl_periodo1`
    FOREIGN KEY (`num_anio_ck` , `num_periodo_ck`)
    REFERENCES `bd_autoscraping`.`tbl_periodo` (`num_anio_pk` , `num_periodo_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_forma_03_tbl_estudiante1`
    FOREIGN KEY (`num_cuenta_ck`)
    REFERENCES `bd_autoscraping`.`tbl_estudiante` (`num_cuenta_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_autoscraping`.`tbl_asignatura_predecida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_autoscraping`.`tbl_asignatura_predecida` (
  `num_cuenta_ck` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cod_asignatura_x_plan_estudio_ck` INT NOT NULL,
  `num_anio_ck` INT(11) NOT NULL,
  `num_periodo_ck` INT(11) NOT NULL,
  `bol_predecida` TINYINT NULL,
  `num_periodos_inactivo` INT NULL,
  INDEX `fk_tbl_predicciones_tbl_asignatura_x_plan_estudio1_idx` (`cod_asignatura_x_plan_estudio_ck` ASC),
  INDEX `fk_tbl_predicciones_tbl_periodo1_idx` (`num_anio_ck` ASC, `num_periodo_ck` ASC),
  PRIMARY KEY (`cod_asignatura_x_plan_estudio_ck`, `num_anio_ck`, `num_periodo_ck`, `num_cuenta_ck`),
  INDEX `fk_tbl_predicciones_tbl_estudiante1_idx` (`num_cuenta_ck` ASC),
  CONSTRAINT `fk_tbl_predicciones_tbl_asignatura_x_plan_estudio1`
    FOREIGN KEY (`cod_asignatura_x_plan_estudio_ck`)
    REFERENCES `bd_autoscraping`.`tbl_asignatura_x_plan_estudio` (`cod_asignatura_x_plan_estudio_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_predicciones_tbl_periodo1`
    FOREIGN KEY (`num_anio_ck` , `num_periodo_ck`)
    REFERENCES `bd_autoscraping`.`tbl_periodo` (`num_anio_pk` , `num_periodo_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_predicciones_tbl_estudiante1`
    FOREIGN KEY (`num_cuenta_ck`)
    REFERENCES `bd_autoscraping`.`tbl_estudiante` (`num_cuenta_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ahac` ;

-- -----------------------------------------------------
-- Table `ahac`.`aeronavefabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`aeronavefabricante` (
  `AerFabKey` INT(11) NOT NULL AUTO_INCREMENT,
  `AerFabDescripcion` VARCHAR(450) NULL DEFAULT NULL,
  `AerFabCodigo` CHAR(50) NULL DEFAULT NULL,
  `AerFabEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`AerFabKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 1523
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`aeronavetipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`aeronavetipo` (
  `AerTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `AerTipDesignador` CHAR(5) NULL DEFAULT NULL,
  `AerFabKey` INT(11) NULL DEFAULT NULL,
  `AerTipDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `AerTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `AerTipEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`AerTipKey`),
  INDEX `FK_AerTipFabricante` (`AerFabKey` ASC),
  CONSTRAINT `FK_AerTipFabricante`
    FOREIGN KEY (`AerFabKey`)
    REFERENCES `ahac`.`aeronavefabricante` (`AerFabKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 2520
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`pais` (
  `PaiKey` INT(11) NOT NULL AUTO_INCREMENT,
  `PaiNombre` VARCHAR(100) NULL DEFAULT NULL,
  `PaiDesignadorOACI` CHAR(2) NULL DEFAULT NULL,
  `PaiPaisLocal` TINYINT(1) NULL DEFAULT NULL,
  `PaiCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `PaiEstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PaiKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`ciudad` (
  `CiuKey` INT(11) NOT NULL AUTO_INCREMENT,
  `CiuNombre` VARCHAR(100) NULL DEFAULT NULL,
  `PaiKey` INT(11) NULL DEFAULT NULL,
  `CiuCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `CiuEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`CiuKey`),
  INDEX `FK_CiuPais` (`PaiKey` ASC),
  CONSTRAINT `FK_CiuPais`
    FOREIGN KEY (`PaiKey`)
    REFERENCES `ahac`.`pais` (`PaiKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`aeropuerto` (
  `ArpKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ArpNombre` VARCHAR(200) NULL DEFAULT NULL,
  `ArpCodigoOACI` CHAR(4) NULL DEFAULT NULL,
  `ArpCodigoIATA` CHAR(3) NULL DEFAULT NULL,
  `ArpLatitud` DECIMAL(9,6) NULL DEFAULT NULL,
  `ArpLongitud` DECIMAL(10,6) NULL DEFAULT NULL,
  `CiuKey` INT(11) NULL DEFAULT NULL,
  `ArpControlado` TINYINT(1) NULL DEFAULT NULL,
  `ArpCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ArpEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`ArpKey`),
  UNIQUE INDEX `U_ArpCodigoOACI` (`ArpCodigoOACI` ASC),
  INDEX `FK_ArpCiudad` (`CiuKey` ASC),
  CONSTRAINT `FK_ArpCiudad`
    FOREIGN KEY (`CiuKey`)
    REFERENCES `ahac`.`ciudad` (`CiuKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`appparametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`appparametro` (
  `PrmKey` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Llave',
  `PrmEmpresaNombre` VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'Instalación / Nombre de la empresa ',
  `PrmEmpresaAcronimo` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'Instalación / Acrónimo de la empresa ',
  `PrmEmpresaLogo` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Instalación / Logo de la empresa',
  `PrmEmpresaUnidadPropietario` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Instalación / Unidad propietario de la instalación en la empresa ',
  `PrmEstructura` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Aplicación / Fecha de Estructura de la base datos',
  `PrmPassValidity` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'Clave de usuario / Días de Vigencia',
  `PrmPassLength` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'Clave de usuario / Longitud',
  `PrmPassTried` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'Clave de usuario / Máximo de intento fallidos permitidos',
  `PrmPassAlphanum` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'Clave de usuario / Debe ser alfanumérica 1= S\'i 0=No',
  `PrmPassRegex` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Clave de usuario / Expresión regular',
  `PrmPassReglas` VARCHAR(500) NULL DEFAULT NULL,
  `PrmPassUsedBefore` TINYINT(3) NOT NULL DEFAULT '0' COMMENT 'Clave de usuario / Cantidad de Claves Anteriores a validar',
  `PrmFechaModi` DATE NULL DEFAULT NULL COMMENT 'Fecha de Modificación',
  `PrmUserM` CHAR(20) NOT NULL DEFAULT '' COMMENT 'Usuario Modificador',
  PRIMARY KEY (`PrmKey`),
  UNIQUE INDEX `appparametros` (`PrmKey` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ahac`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`archivo` (
  `ArchKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ArchNombre` VARCHAR(500) NULL DEFAULT NULL,
  `ArchExtension` VARCHAR(20) NULL DEFAULT NULL,
  `ArchBlob` BLOB NULL DEFAULT NULL,
  `ArchCodigo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ArchKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`operador` (
  `OpeKey` INT(11) NOT NULL AUTO_INCREMENT,
  `OpeDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `OpeCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `OpeEstatus` INT(11) NULL DEFAULT NULL,
  `PaiKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`OpeKey`),
  INDEX `FK_OpePais` (`PaiKey` ASC),
  CONSTRAINT `FK_OpePais`
    FOREIGN KEY (`PaiKey`)
    REFERENCES `ahac`.`pais` (`PaiKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`operadordesignador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`operadordesignador` (
  `OpeDsgKey` INT(11) NOT NULL AUTO_INCREMENT,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDsgDesignadorOACI` VARCHAR(3) NULL DEFAULT NULL,
  `OpeDsgDesignadorIATA` VARCHAR(2) NULL DEFAULT NULL,
  `OpeDsgCodigo` CHAR(3) NULL DEFAULT NULL,
  `OpeDsgEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`OpeDsgKey`),
  INDEX `FK_OpeDsgOperador` (`OpeKey` ASC),
  CONSTRAINT `FK_OpeDsgOperador`
    FOREIGN KEY (`OpeKey`)
    REFERENCES `ahac`.`operador` (`OpeKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`crgpsjbitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`crgpsjbitacora` (
  `CrgPsjBtcKey` INT(11) NOT NULL AUTO_INCREMENT,
  `CrgPsjBtcFecha` DATE NULL DEFAULT NULL,
  `CrgPsjBtcHora` TIME NULL DEFAULT NULL,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `OpeDsgKey` INT(11) NULL DEFAULT NULL,
  `OpeDsgDesignadorOACI` CHAR(3) NULL DEFAULT NULL,
  `CrgPsjBtcArchivo` BLOB NULL DEFAULT NULL,
  `CrgPsjBtcArchivoNombre` VARCHAR(255) NULL DEFAULT NULL,
  `CrgPsjBtcArchivoExtension` VARCHAR(20) NULL DEFAULT NULL,
  `CrgPsjBtcAnio` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcMes` TINYINT(4) NULL DEFAULT NULL,
  `SegUsrKey` INT(11) NULL DEFAULT NULL,
  `CrgPsjBtcSinDatos` TINYINT(1) NULL DEFAULT NULL,
  `CrgPsjBtcObservaciones` TEXT NULL DEFAULT NULL,
  `CrgPsjBtcLineasCargadas` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcEjecucionETL` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcEjecucionBI` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcCargaATiempo` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcDiasRetraso` SMALLINT(6) NULL DEFAULT NULL,
  `CrgPsjBtcEstatus` TINYINT(4) NULL DEFAULT NULL,
  `CrgPsjBtcComprobanteArchivo` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`CrgPsjBtcKey`),
  INDEX `FK_CrgPsjBtcOperador` (`OpeKey` ASC),
  INDEX `FK_CrgPsjBtcOpeDesignador` (`OpeDsgKey` ASC),
  CONSTRAINT `FK_CrgPsjBtcOpeDesignador`
    FOREIGN KEY (`OpeDsgKey`)
    REFERENCES `ahac`.`operadordesignador` (`OpeDsgKey`),
  CONSTRAINT `FK_CrgPsjBtcOperador`
    FOREIGN KEY (`OpeKey`)
    REFERENCES `ahac`.`operador` (`OpeKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 1268
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`crgpsjestructuraarchivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`crgpsjestructuraarchivo` (
  `CrgPsjEstruArchKey` INT(11) NOT NULL AUTO_INCREMENT,
  `CrgPsjEstruArchColumnaNumero` INT(11) NULL DEFAULT '0',
  `CrgPsjEstruArchColumnaTitulo` VARCHAR(50) NULL DEFAULT '0',
  `CrgPsjEstruArchTipoDato` VARCHAR(20) NULL DEFAULT '0',
  `CrgPsjEstruArchAceptaDecimales` TINYINT(1) NULL DEFAULT '0',
  `CrgPsjEstruArchValidarRegex` TINYINT(1) NULL DEFAULT '0',
  `CrgPsjEstruArchRegex` VARCHAR(50) NULL DEFAULT '0',
  `CrgPsjEstruArchValidarFuncion` TINYINT(1) NULL DEFAULT '0',
  `CrgPsjEstruArchFuncion` VARCHAR(100) NULL DEFAULT '0',
  `CrgPsjEstruArchParametrosExtra` VARCHAR(200) NULL DEFAULT '0',
  `CrgPsjEstruArchMensaje` VARCHAR(200) NULL DEFAULT '0',
  PRIMARY KEY (`CrgPsjEstruArchKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`crgpsjvuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`crgpsjvuelo` (
  `CrgPsjKey` INT(11) NOT NULL AUTO_INCREMENT,
  `CrgPsjBtcKey` INT(11) NULL DEFAULT NULL,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `OpeDsgKey` INT(11) NULL DEFAULT NULL,
  `OpeDsgDesignadorOACI` CHAR(3) NULL DEFAULT NULL,
  `CrgPsjVueloFecha` DATE NULL DEFAULT NULL,
  `VueCatKey` INT(11) NULL DEFAULT NULL,
  `VueCatDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `CrgPsjAeropuertoOrigenArpKey` INT(11) NULL DEFAULT NULL,
  `CrgPsjAeropuertoOrigen` CHAR(4) NULL DEFAULT NULL,
  `CrgPsjAeropuertoDestinoArpKey` INT(11) NULL DEFAULT NULL,
  `CrgPsjAeropuertoDestino` CHAR(4) NULL DEFAULT NULL,
  `CrgPsjVueloNumero` CHAR(5) NULL DEFAULT NULL,
  `CrgPsjRuta` VARCHAR(20) NULL DEFAULT NULL,
  `CrgPsjKmVolados` DECIMAL(8,2) NULL DEFAULT NULL,
  `AerTipKey` INT(11) NULL DEFAULT NULL,
  `AerTipDesignador` VARCHAR(20) NULL DEFAULT NULL,
  `CrgPsjTiempoVuelo` MEDIUMINT(6) NULL DEFAULT NULL,
  `CrgPsjHoraUTC` CHAR(4) NULL DEFAULT NULL,
  `CrgPsjHoraLocal` CHAR(4) NULL DEFAULT NULL,
  `CrgPsjPasajeros` INT(11) NULL DEFAULT NULL,
  `CrgPsjCarga` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`CrgPsjKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 11554
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encserviciocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encserviciocategoria` (
  `EncSrvCatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncSrvCatCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncSrvCatDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncSrvCatEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`EncSrvCatKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestatipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestatipo` (
  `EncEncTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncEncTipDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncSrvCatKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipFechaActivacion` DATE NULL DEFAULT NULL,
  `EncEncTipFechaInactivacion` DATE NULL DEFAULT NULL,
  `EncEncTipEstatus` TINYINT(1) NULL DEFAULT NULL,
  `EncEncTipPreKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipVersion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncTipKey`),
  INDEX `FK_EncTipServicioCategoria` (`EncSrvCatKey` ASC),
  INDEX `FK_EncTipPregunta` (`EncEncTipPreKey` ASC),
  CONSTRAINT `FK_EncTipServicioCategoria`
    FOREIGN KEY (`EncSrvCatKey`)
    REFERENCES `ahac`.`encserviciocategoria` (`EncSrvCatKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encjornadaaplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encjornadaaplicacion` (
  `EncJorAplKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncEncTipVersion` INT(11) NULL DEFAULT NULL,
  `EncJorAplFechaInicioVigencia` DATE NULL DEFAULT NULL,
  `EncJorAplFechaFinVigencia` DATE NULL DEFAULT NULL,
  `EncJorAplDescripcion` VARCHAR(500) NULL DEFAULT NULL,
  `SegUsrKey` INT(11) NULL DEFAULT NULL,
  `EncJorAplFechaFinalizacion` DATE NULL DEFAULT NULL,
  `SegUsrKeyFinalizacion` INT(11) NULL DEFAULT NULL,
  `EncJorAplFinalizacionObservaciones` VARCHAR(500) NULL DEFAULT NULL,
  `EncJorAplFechaAnulacion` DATE NULL DEFAULT NULL,
  `EncJorAplAnulacionObservaciones` VARCHAR(500) NULL DEFAULT NULL,
  `SegUsrKeyAnulacion` INT(11) NULL DEFAULT NULL,
  `EncJorAplEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EncJorAplKey`),
  INDEX `FK_EncJorAplEncuestaTipo` (`EncEncTipKey` ASC),
  CONSTRAINT `FK_EncJorAplEncuestaTipo`
    FOREIGN KEY (`EncEncTipKey`)
    REFERENCES `ahac`.`encencuestatipo` (`EncEncTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestaaplicada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestaaplicada` (
  `EncEncAplKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncJorAplKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncEncTipVersion` INT(11) NULL DEFAULT NULL,
  `EncEncTipDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncEncSrvCatKey` INT(11) NULL DEFAULT NULL,
  `EncSrvCatDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncEcdCatKey` INT(11) NULL DEFAULT NULL,
  `EncEcdCatDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncEncAplFecha` DATE NULL DEFAULT NULL,
  `EncEncAplHora` TIME NULL DEFAULT NULL,
  `SegUsrKey` INT(11) NULL DEFAULT NULL,
  `ArpKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncAplKey`),
  INDEX `I_EncEncTipKey` (`EncEncTipKey` ASC),
  INDEX `I_JorArpEcdCat` (`EncJorAplKey` ASC, `EncEcdCatKey` ASC, `ArpKey` ASC, `EncEncAplKey` ASC),
  INDEX `I_EncEncTipCodigo` (`EncEncTipCodigo` ASC),
  CONSTRAINT `FK_EncEncAplJornadaAplicacion`
    FOREIGN KEY (`EncJorAplKey`)
    REFERENCES `ahac`.`encjornadaaplicacion` (`EncJorAplKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 157
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestaaplicadarespuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestaaplicadarespuesta` (
  `EncEncAplResKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncAplKey` INT(11) NULL DEFAULT NULL,
  `EncJorAplKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreGruKey` INT(11) NULL DEFAULT NULL,
  `EncResTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreOpcKey` INT(11) NULL DEFAULT NULL,
  `EncPreCtlgKey` INT(11) NULL DEFAULT NULL,
  `EncEcdCatKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreOpcDescripcion` VARCHAR(500) NULL DEFAULT NULL,
  `EncEncTipPreOpcTexto` VARCHAR(500) NULL DEFAULT NULL,
  `ArpKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncAplResKey`),
  INDEX `I_JorArpEcdCatRespuesta` (`EncJorAplKey` ASC, `EncEcdCatKey` ASC, `ArpKey` ASC),
  INDEX `I_PreArpEcdCatRespuesta` (`EncEncTipPreKey` ASC, `ArpKey` ASC, `EncEcdCatKey` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1801
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestadocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestadocategoria` (
  `EncEcdCatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEcdCatCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncEcdCatDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncEcdCatEstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEcdCatKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestatipoencuestadocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestatipoencuestadocategoria` (
  `EncEncTipKey` INT(11) NOT NULL,
  `EncEcdCatKey` INT(11) NOT NULL,
  PRIMARY KEY (`EncEncTipKey`, `EncEcdCatKey`),
  INDEX `FK_EncEncTipEcdEncuestadoCategoria` (`EncEcdCatKey` ASC),
  CONSTRAINT `FK_EncEncTipEcdEncuestaTipo`
    FOREIGN KEY (`EncEncTipKey`)
    REFERENCES `ahac`.`encencuestatipo` (`EncEncTipKey`),
  CONSTRAINT `FK_EncEncTipEcdEncuestadoCategoria`
    FOREIGN KEY (`EncEcdCatKey`)
    REFERENCES `ahac`.`encencuestadocategoria` (`EncEcdCatKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestatipopreguntagrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestatipopreguntagrupo` (
  `EncEncTipPreGruKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreGruCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncEncTipPreGruDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncEncTipPreGruOrden` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreGruEstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncTipPreGruKey`),
  INDEX `FK_EncEncTipPreGru_EncuestaTipo` (`EncEncTipKey` ASC),
  CONSTRAINT `FK_EncEncTipPreGru_EncuestaTipo`
    FOREIGN KEY (`EncEncTipKey`)
    REFERENCES `ahac`.`encencuestatipo` (`EncEncTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 145
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encrespuestatipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encrespuestatipo` (
  `EncResTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncResTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `EncResTipDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `EncResTipEstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`EncResTipKey`),
  UNIQUE INDEX `U_EncResTipCodigo` (`EncResTipCodigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestatipopregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestatipopregunta` (
  `EncEncTipPreKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreGruKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreDescripcion` VARCHAR(500) NULL DEFAULT NULL,
  `EncResTipKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreOrden` INT(11) NULL DEFAULT NULL,
  `EncPreCtlgKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncTipPreKey`),
  INDEX `FK_EncTipPreEncuestaTipo` (`EncEncTipKey` ASC),
  INDEX `FK_EncTipPrePreguntaGrupo` (`EncEncTipPreGruKey` ASC),
  INDEX `FK_EncTipPreRespuestaTipo` (`EncResTipKey` ASC),
  CONSTRAINT `FK_EncTipPreEncuestaTipo`
    FOREIGN KEY (`EncEncTipKey`)
    REFERENCES `ahac`.`encencuestatipo` (`EncEncTipKey`),
  CONSTRAINT `FK_EncTipPrePreguntaGrupo`
    FOREIGN KEY (`EncEncTipPreGruKey`)
    REFERENCES `ahac`.`encencuestatipopreguntagrupo` (`EncEncTipPreGruKey`),
  CONSTRAINT `FK_EncTipPreRespuestaTipo`
    FOREIGN KEY (`EncResTipKey`)
    REFERENCES `ahac`.`encrespuestatipo` (`EncResTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 267
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encencuestatipopreguntaopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encencuestatipopreguntaopcion` (
  `EncEncTipPreOpcKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncEncTipPreKey` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreOpcDescripcion` VARCHAR(500) NULL DEFAULT NULL,
  `EncEncTipPreOpcOrden` INT(11) NULL DEFAULT NULL,
  `EncEncTipPreOpcIncluyeTexto` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`EncEncTipPreOpcKey`),
  INDEX `FK_EncTipPreOpcPregunta` (`EncEncTipPreKey` ASC),
  CONSTRAINT `FK_EncTipPreOpcPregunta`
    FOREIGN KEY (`EncEncTipPreKey`)
    REFERENCES `ahac`.`encencuestatipopregunta` (`EncEncTipPreKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 516
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`encpreguntacatalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`encpreguntacatalogo` (
  `EncPreCtlgKey` INT(11) NOT NULL AUTO_INCREMENT,
  `EncPreCtlgNombreCatalogo` VARCHAR(100) NULL DEFAULT NULL,
  `EncPreCtlgFuncion` VARCHAR(50) NULL DEFAULT NULL,
  `EncPreCtlgFuncionByKey` VARCHAR(50) NULL DEFAULT NULL,
  `EncPreCtlgEstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`EncPreCtlgKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`iticapacidadrangotiempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`iticapacidadrangotiempo` (
  `ItiCapRngoTmpKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiCapRngTmpDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `ItiCapRngTmpDia` TINYINT(1) NULL DEFAULT NULL,
  `ItiCapRngTmpLimiteInferior` CHAR(5) NULL DEFAULT NULL,
  `ItiCapRngTmpLimiteSuperior` CHAR(5) NULL DEFAULT NULL,
  `ItiCapRngTmpCapacidad` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiCapRngoTmpKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itiescalacumplimientoestructura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itiescalacumplimientoestructura` (
  `ItiScaCmpEstruKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiScaCmpEstruDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `ItiScaCmpEstruFechaInicio` DATE NULL DEFAULT NULL,
  `ItiScaCmpEstruFechaFin` DATE NULL DEFAULT NULL,
  `ItiScaCmpEstruValida` INT(1) NULL DEFAULT NULL,
  `ItiScaCmpEstruObservaciones` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiScaCmpEstruKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itiescalacumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itiescalacumplimiento` (
  `ItiScaCmpKey` INT(11) NOT NULL,
  `ItiScaCmpEstruKey` INT(11) NOT NULL,
  `ItiScaCmpDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `ItiScaCmpLimiteInferior` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpLimiteSuperior` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpColorHex` CHAR(7) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiScaCmpKey`, `ItiScaCmpEstruKey`),
  INDEX `FK_ItiEscalaCumplimientoEstructura` (`ItiScaCmpEstruKey` ASC),
  CONSTRAINT `FK_ItiEscalaCumplimientoEstructura`
    FOREIGN KEY (`ItiScaCmpEstruKey`)
    REFERENCES `ahac`.`itiescalacumplimientoestructura` (`ItiScaCmpEstruKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizaciontipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizaciontipo` (
  `ItiAutTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiAutTipDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `ItiAutTipOperadorNacionalidad` INT(11) NULL DEFAULT NULL,
  `ItiAutTipEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizaciontiponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizaciontiponivel` (
  `ItiAutTipNivKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutTipKey` INT(11) NULL DEFAULT NULL,
  `ItiAutTipNivDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `ItiAutTipNivCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiAutTipNivNoVueloObligatorio` INT(11) NULL DEFAULT NULL,
  `ItiAutTipNivEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutTipNivKey`),
  INDEX `FK_TipNivTipo` (`ItiAutTipKey` ASC),
  CONSTRAINT `FK_TipNivTipo`
    FOREIGN KEY (`ItiAutTipKey`)
    REFERENCES `ahac`.`itinerarioautorizaciontipo` (`ItiAutTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioestatuscat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioestatuscat` (
  `ItiEstCatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiEstCatCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiEstCatDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `ItiEstCatEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiEstCatKey`),
  UNIQUE INDEX `UItiEstCatCodigo` (`ItiEstCatCodigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioestatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioestatus` (
  `ItiEstKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiEstCatKey` INT(11) NULL DEFAULT NULL,
  `ItiEstCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiEstDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `ItiEstEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiEstKey`),
  INDEX `FK_ItiEstCatCategoria` (`ItiEstCatKey` ASC),
  CONSTRAINT `FK_ItiEstCatCategoria`
    FOREIGN KEY (`ItiEstCatKey`)
    REFERENCES `ahac`.`itinerarioestatuscat` (`ItiEstCatKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizacion` (
  `ItiAutKey` INT(11) NOT NULL AUTO_INCREMENT,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDsgKey` INT(11) NULL DEFAULT NULL,
  `ItiAutAutorizacionNo` VARCHAR(15) NULL DEFAULT NULL,
  `ItiAutTipKey` INT(11) NULL DEFAULT NULL,
  `ItiAutTipNivKey` INT(11) NULL DEFAULT NULL,
  `ItiAutRutas` TEXT NULL DEFAULT NULL,
  `ItiEstKey` INT(11) NULL DEFAULT NULL,
  `ItiAutOficial` TINYINT(4) NULL DEFAULT NULL,
  `ItiAutFechaInicioVigencia` DATE NULL DEFAULT NULL,
  `ItiAutFechaFinVigencia` DATE NULL DEFAULT NULL,
  `ItiAutFechaMinCambios` DATE NULL DEFAULT NULL,
  `ItiAutAmpliacionAutomatica` TINYINT(1) NULL DEFAULT NULL,
  `ItiAutBitacoraCambios` LONGTEXT NULL DEFAULT NULL,
  `ItiAutKeyOriginal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutKey`),
  INDEX `FK_ItiAutOpe` (`OpeKey` ASC),
  INDEX `FK_ItiAutTip` (`ItiAutTipKey` ASC),
  INDEX `FK_ItiAutItiTipNiv` (`ItiAutTipNivKey` ASC),
  INDEX `FK_ItiEstEstatus` (`ItiEstKey` ASC),
  INDEX `FK_ItiAutOpeDsg` (`OpeDsgKey` ASC),
  CONSTRAINT `FK_ItiAutOpe`
    FOREIGN KEY (`OpeKey`)
    REFERENCES `ahac`.`operador` (`OpeKey`),
  CONSTRAINT `FK_ItiAutOpeDsg`
    FOREIGN KEY (`OpeDsgKey`)
    REFERENCES `ahac`.`operadordesignador` (`OpeDsgKey`),
  CONSTRAINT `FK_ItiAutTipo`
    FOREIGN KEY (`ItiAutTipKey`)
    REFERENCES `ahac`.`itinerarioautorizaciontipo` (`ItiAutTipKey`),
  CONSTRAINT `FK_ItiAutTipoNivel`
    FOREIGN KEY (`ItiAutTipNivKey`)
    REFERENCES `ahac`.`itinerarioautorizaciontiponivel` (`ItiAutTipNivKey`),
  CONSTRAINT `FK_ItiEstEstatus`
    FOREIGN KEY (`ItiEstKey`)
    REFERENCES `ahac`.`itinerarioestatus` (`ItiEstKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizaciongestiontipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizaciongestiontipo` (
  `ItiAutGstTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutGstTipCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiAutGstTipDescripcion` VARCHAR(200) NULL DEFAULT NULL,
  `ItiAutGstTipEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutGstTipKey`),
  UNIQUE INDEX `UItiAutGstTipCodigo` (`ItiAutGstTipCodigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizaciongestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizaciongestion` (
  `ItiAutGstKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutKey` INT(11) NULL DEFAULT NULL,
  `ItiAutGstTipKey` INT(11) NULL DEFAULT NULL,
  `ItiAutGstFecha` DATE NULL DEFAULT NULL,
  `ItiAutGstFechaHora` DATETIME NULL DEFAULT NULL,
  `ItiAutGstUsuario` VARCHAR(50) NULL DEFAULT NULL,
  `ItiAutGstAeropuerto` CHAR(4) NULL DEFAULT NULL,
  `ItiAutGstJustificacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutGstKey`),
  INDEX `FK_ItiAutGstTipo` (`ItiAutGstTipKey` ASC),
  INDEX `FK_ItiAutGstAutorizacion` (`ItiAutKey` ASC),
  CONSTRAINT `FK_ItiAutGstAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`),
  CONSTRAINT `FK_ItiAutGstTipo`
    FOREIGN KEY (`ItiAutGstTipKey`)
    REFERENCES `ahac`.`itinerarioautorizaciongestiontipo` (`ItiAutGstTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariomodalidadtrafico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariomodalidadtrafico` (
  `ItiModTraKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiModTraCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `ItiModTraDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `ItiModTraEstatus` INT(11) NULL DEFAULT NULL,
  `ItiModTraFechaInicio` DATE NULL DEFAULT NULL,
  `ItiModTraFechaFin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ItiModTraKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerarioautorizacionmodtrafico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerarioautorizacionmodtrafico` (
  `ItiAutModTraKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutKey` INT(11) NULL DEFAULT NULL,
  `ItiModTraKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutModTraKey`),
  INDEX `FK_ModTraItinerarioAutorizacion` (`ItiAutKey` ASC),
  INDEX `FK_ModTrafico` (`ItiModTraKey` ASC),
  CONSTRAINT `FK_ModTraItinerarioAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`),
  CONSTRAINT `FK_ModTrafico`
    FOREIGN KEY (`ItiModTraKey`)
    REFERENCES `ahac`.`itinerariomodalidadtrafico` (`ItiModTraKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 139
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariofecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariofecha` (
  `ItiAutFchKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutFchFecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutFchKey`),
  INDEX `I_ItiAutFchFecha` (`ItiAutFchFecha` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2333
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariofechacontrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariofechacontrol` (
  `ItiFchCtrlKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutFchKey` INT(11) NULL DEFAULT NULL,
  `ItiFchCtrlEstatus` CHAR(1) NULL DEFAULT 'N',
  `ItiFchCtrlFechaHoraEjecucion` DATETIME NULL DEFAULT NULL,
  `EncJorAplEstatus` CHAR(1) NULL DEFAULT NULL,
  `EncJorAplFechaHoraEjecucion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ItiFchCtrlKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 161
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariomatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariomatricula` (
  `ItiAutMatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutKey` INT(11) NULL DEFAULT NULL,
  `OpeMatKey` INT(11) NULL DEFAULT NULL,
  `ItiAutMatMatricula` VARCHAR(10) NULL DEFAULT NULL,
  `AerTipKey` INT(11) NULL DEFAULT NULL,
  `AerTipDesignador` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutMatKey`),
  INDEX `FK_ItiAutMatAerTip` (`AerTipKey` ASC),
  INDEX `FK_ItiAutMatAutorizacion` (`ItiAutKey` ASC),
  CONSTRAINT `FK_ItiAutMatAerTip`
    FOREIGN KEY (`AerTipKey`)
    REFERENCES `ahac`.`aeronavetipo` (`AerTipKey`),
  CONSTRAINT `FK_ItiAutMatAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariofechamatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariofechamatricula` (
  `ItiAutKey` INT(11) NOT NULL,
  `ItiAutFchKey` INT(11) NOT NULL,
  `ItiAutMatKey` INT(11) NOT NULL,
  `ItiAutFchFecha` DATE NULL DEFAULT NULL,
  `ItiAutAutorizacionNo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutKey`, `ItiAutFchKey`, `ItiAutMatKey`),
  INDEX `FK_ItiAutFchMatFecha` (`ItiAutFchKey` ASC),
  INDEX `FK_ItiAutMatKeyMatricula` (`ItiAutMatKey` ASC),
  CONSTRAINT `FK_ItiAutFchMatFecha`
    FOREIGN KEY (`ItiAutFchKey`)
    REFERENCES `ahac`.`itinerariofecha` (`ItiAutFchKey`),
  CONSTRAINT `FK_ItiAutKeyMatAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`),
  CONSTRAINT `FK_ItiAutMatKeyMatricula`
    FOREIGN KEY (`ItiAutMatKey`)
    REFERENCES `ahac`.`itinerariomatricula` (`ItiAutMatKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariovuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariovuelo` (
  `ItiAutVueKey` INT(11) NOT NULL AUTO_INCREMENT,
  `ItiAutKey` INT(11) NULL DEFAULT NULL,
  `ItiAutVueVueloNumero` CHAR(5) NULL DEFAULT NULL,
  `ItiAutVueHoraSalida` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueHoraLlegada` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueHoraLlegadaDiaDistinto` SMALLINT(1) NULL DEFAULT NULL,
  `ItiAutVueOrigenArpKey` INT(11) NULL DEFAULT NULL,
  `ItiAutVueOrigen` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueDestinoArpKey` INT(11) NULL DEFAULT NULL,
  `ItiAutVueDestino` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueFechas` TEXT NULL DEFAULT NULL,
  `ItiAutVueFrecuencia` TEXT NULL DEFAULT NULL,
  `ItiAutVuePatronGeneracion` TEXT NULL DEFAULT NULL,
  `ItiAutVueKeyOriginal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutVueKey`),
  INDEX `FK_ItiAutVueAutorizacion` (`ItiAutKey` ASC),
  INDEX `FK_ItiAutVueAeropuertoOrigen` (`ItiAutVueOrigenArpKey` ASC),
  INDEX `FK_ItiAutVueAeropuertoDestino` (`ItiAutVueDestinoArpKey` ASC),
  CONSTRAINT `FK_ItiAutVueAeropuertoDestino`
    FOREIGN KEY (`ItiAutVueDestinoArpKey`)
    REFERENCES `ahac`.`aeropuerto` (`ArpKey`),
  CONSTRAINT `FK_ItiAutVueAeropuertoOrigen`
    FOREIGN KEY (`ItiAutVueOrigenArpKey`)
    REFERENCES `ahac`.`aeropuerto` (`ArpKey`),
  CONSTRAINT `FK_ItiAutVueAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 167
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`itinerariofechavuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`itinerariofechavuelo` (
  `ItiAutKey` INT(11) NOT NULL,
  `ItiAutFchKey` INT(11) NOT NULL,
  `ItiAutVueKey` INT(11) NOT NULL,
  `ItiAutFchFecha` DATE NULL DEFAULT NULL,
  `ItiAutAutorizacionNo` VARCHAR(15) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDEP` TINYINT(1) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDiaDistintoDEP` TINYINT(1) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDifMinDEP` SMALLINT(4) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDifIgualMayorMenorDEP` TINYINT(1) NULL DEFAULT NULL,
  `ItiScaCmpKeyDEP` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpEstruKeyDEP` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpColorHexDEP` CHAR(7) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoARR` TINYINT(1) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDiaDistintoARR` TINYINT(1) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDifMinARR` SMALLINT(4) NULL DEFAULT NULL,
  `ItiAutFchVueloOperadoDifIgualMayorMenorARR` TINYINT(1) NULL DEFAULT NULL,
  `ItiScaCmpKeyARR` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpEstruKeyARR` INT(11) NULL DEFAULT NULL,
  `ItiScaCmpColorHexARR` CHAR(7) NULL DEFAULT NULL,
  `VueOpeKey` INT(11) NULL DEFAULT NULL,
  `VueOpeKey_B` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ItiAutFchKey`, `ItiAutVueKey`, `ItiAutKey`),
  INDEX `I_ItiAutFchFecha` (`ItiAutFchFecha` ASC),
  INDEX `FK_ItiAutFchAutorizacion` (`ItiAutKey` ASC),
  INDEX `FK_ItiAutFchVuelo` (`ItiAutVueKey` ASC),
  CONSTRAINT `FK_ItiAutFchAutorizacion`
    FOREIGN KEY (`ItiAutKey`)
    REFERENCES `ahac`.`itinerarioautorizacion` (`ItiAutKey`),
  CONSTRAINT `FK_ItiAutFchFecha`
    FOREIGN KEY (`ItiAutFchKey`)
    REFERENCES `ahac`.`itinerariofecha` (`ItiAutFchKey`),
  CONSTRAINT `FK_ItiAutFchVuelo`
    FOREIGN KEY (`ItiAutVueKey`)
    REFERENCES `ahac`.`itinerariovuelo` (`ItiAutVueKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`operadormatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`operadormatricula` (
  `OpeMatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `AerTipKey` INT(11) NULL DEFAULT NULL,
  `OpeMatMatricula` VARCHAR(10) NULL DEFAULT NULL,
  `OpeMatCodigo` VARCHAR(50) NULL DEFAULT NULL,
  `OpeMatEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`OpeMatKey`),
  INDEX `FK_OpeMat` (`OpeKey` ASC),
  INDEX `FK_OpeMatAerTip` (`AerTipKey` ASC),
  CONSTRAINT `FK_OpeMat`
    FOREIGN KEY (`OpeKey`)
    REFERENCES `ahac`.`operador` (`OpeKey`),
  CONSTRAINT `FK_OpeMatAerTip`
    FOREIGN KEY (`AerTipKey`)
    REFERENCES `ahac`.`aeronavetipo` (`AerTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`parametro` (
  `PrmCodigo` CHAR(50) NOT NULL,
  `PrmDescripcion` VARCHAR(500) NULL DEFAULT NULL,
  `PrmValor` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`PrmCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`reporte` (
  `RptCodigo` CHAR(20) NOT NULL,
  `RptTitulo` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`RptCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segprograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segprograma` (
  `SegPrgKey` INT(11) NOT NULL AUTO_INCREMENT,
  `SegPrgNombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegPrgDescripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`SegPrgKey`),
  UNIQUE INDEX `U_SegPrgNombre` (`SegPrgNombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`segfuncion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segfuncion` (
  `SegFncKey` INT(11) NOT NULL AUTO_INCREMENT,
  `SegFncNombre` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegPrgKey` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SegFncKey`),
  INDEX `FK_SegFuncionPrograma` (`SegPrgKey` ASC),
  CONSTRAINT `FK_SegFuncionPrograma`
    FOREIGN KEY (`SegPrgKey`)
    REFERENCES `ahac`.`segprograma` (`SegPrgKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 116
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`seglog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`seglog` (
  `SegLogKey` INT(11) NOT NULL AUTO_INCREMENT,
  `SegLogFecha` DATE NULL DEFAULT NULL,
  `SegLogHora` TIME NULL DEFAULT NULL,
  `SegUsrKey` INT(11) NULL DEFAULT NULL,
  `SegUsrUsuario` VARCHAR(20) NULL DEFAULT NULL,
  `SegLogDetalle` MEDIUMTEXT NULL DEFAULT NULL,
  `SegLogLlave` INT(11) NULL DEFAULT NULL,
  `SegLogTabla` VARCHAR(60) NULL DEFAULT NULL,
  `SegLogAccion` MEDIUMTEXT NULL DEFAULT NULL,
  `SegLogComando` MEDIUMTEXT NULL DEFAULT NULL,
  `SegLogIp` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`SegLogKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 15668
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segmenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segmenu` (
  `SegMenuId` INT(11) NOT NULL AUTO_INCREMENT,
  `SegMenuNombre` VARCHAR(50) NULL DEFAULT NULL,
  `SegMenuDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `SegMenuIcono` VARCHAR(40) NULL DEFAULT NULL,
  `SegMenuURL` VARCHAR(200) NULL DEFAULT NULL,
  `SegMenuOrden` INT(11) NULL DEFAULT NULL,
  `SegMenuRaizId` INT(11) NULL DEFAULT NULL,
  `SegMenuActivo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`SegMenuId`),
  INDEX `FK_SegMenu` (`SegMenuRaizId` ASC),
  CONSTRAINT `FK_SegMenu`
    FOREIGN KEY (`SegMenuRaizId`)
    REFERENCES `ahac`.`segmenu` (`SegMenuId`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segrol` (
  `SegRolKey` INT(11) NOT NULL AUTO_INCREMENT,
  `SegRolNombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`SegRolKey`),
  UNIQUE INDEX `U_SegRolNombre` (`SegRolNombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`segrolfuncion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segrolfuncion` (
  `SegRolKey` INT(11) NOT NULL,
  `SegFncKey` INT(11) NOT NULL,
  PRIMARY KEY (`SegRolKey`, `SegFncKey`),
  INDEX `FK_SegRolFuncionFuncion` (`SegFncKey` ASC),
  CONSTRAINT `FK_SegRolFuncionFuncion`
    FOREIGN KEY (`SegFncKey`)
    REFERENCES `ahac`.`segfuncion` (`SegFncKey`),
  CONSTRAINT `FK_SegRolFuncionRol`
    FOREIGN KEY (`SegRolKey`)
    REFERENCES `ahac`.`segrol` (`SegRolKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`segusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segusuario` (
  `SegUsrKey` INT(11) NOT NULL AUTO_INCREMENT,
  `SegUsrUsuario` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegUsrNombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegUsrApellido` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegUsrPassword` VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `ArpKey` INT(11) NULL DEFAULT NULL,
  `SegUsrEstatus` TINYINT(4) NULL DEFAULT NULL,
  `SegUsrCodigo` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `SegUsrCambiarPassword` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`SegUsrKey`),
  UNIQUE INDEX `U_SegUsrUsuario` (`SegUsrUsuario` ASC),
  INDEX `FK_SegUsuarioAeropuerto` (`ArpKey` ASC),
  CONSTRAINT `FK_SegUsuarioAeropuerto`
    FOREIGN KEY (`ArpKey`)
    REFERENCES `ahac`.`aeropuerto` (`ArpKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`segusuarioaeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segusuarioaeropuerto` (
  `SegUsrKey` INT(11) NOT NULL,
  `ArpKey` INT(11) NOT NULL,
  `SegUsrArpCreacion` INT(11) NULL DEFAULT NULL,
  `SegUsrArpModificacion` INT(11) NULL DEFAULT NULL,
  `SegUsrArpEliminacion` INT(11) NULL DEFAULT NULL,
  `SegUsrArpValidacionOperacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SegUsrKey`, `ArpKey`),
  INDEX `FK_SegUsrArpAeropuerto` (`ArpKey` ASC),
  CONSTRAINT `FK_SegUsrArpAeropuerto`
    FOREIGN KEY (`ArpKey`)
    REFERENCES `ahac`.`aeropuerto` (`ArpKey`),
  CONSTRAINT `FK_SegUsrArpSegUsuario`
    FOREIGN KEY (`SegUsrKey`)
    REFERENCES `ahac`.`segusuario` (`SegUsrKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segusuarioencuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segusuarioencuesta` (
  `SegUsrKey` INT(11) NOT NULL,
  `EncEncTipCodigo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SegUsrKey`, `EncEncTipCodigo`),
  CONSTRAINT `FK_SegUsrSegUsuario`
    FOREIGN KEY (`SegUsrKey`)
    REFERENCES `ahac`.`segusuario` (`SegUsrKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segusuariooperador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segusuariooperador` (
  `SegUsrKey` INT(11) NOT NULL,
  `OpeKey` INT(11) NOT NULL,
  PRIMARY KEY (`SegUsrKey`, `OpeKey`),
  INDEX `FK_SegUsrOpeOperador` (`OpeKey` ASC),
  CONSTRAINT `FK_SegUsrOpeOperador`
    FOREIGN KEY (`OpeKey`)
    REFERENCES `ahac`.`operador` (`OpeKey`),
  CONSTRAINT `FK_SegUsrOpeUsuario`
    FOREIGN KEY (`SegUsrKey`)
    REFERENCES `ahac`.`segusuario` (`SegUsrKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`segusuariorol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`segusuariorol` (
  `SegUsrKey` INT(11) NOT NULL,
  `SegRolKey` INT(11) NOT NULL,
  PRIMARY KEY (`SegUsrKey`, `SegRolKey`),
  INDEX `FK_SegUsuarioRolRol` (`SegRolKey` ASC),
  CONSTRAINT `FK_SegUsuarioRolRol`
    FOREIGN KEY (`SegRolKey`)
    REFERENCES `ahac`.`segrol` (`SegRolKey`),
  CONSTRAINT `FK_SegUsuarioRolUsr`
    FOREIGN KEY (`SegUsrKey`)
    REFERENCES `ahac`.`segusuario` (`SegUsrKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `ahac`.`vuelocategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`vuelocategoria` (
  `VueCatKey` INT(11) NOT NULL AUTO_INCREMENT,
  `VueCatDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `VueCatCodigo` VARCHAR(10) NULL DEFAULT NULL,
  `VueCatEstatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`VueCatKey`),
  UNIQUE INDEX `U_VueCatDescripcion` (`VueCatDescripcion` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`vuelooperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`vuelooperacion` (
  `VueOpeKey` INT(11) NOT NULL AUTO_INCREMENT,
  `VueTipKey` INT(11) NULL DEFAULT NULL,
  `VueTipDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `VueCatKey` INT(11) NULL DEFAULT NULL,
  `VueCatDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `OpeDsgKey` INT(11) NULL DEFAULT NULL,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `OpeDsgDesignadorOACI` CHAR(10) NULL DEFAULT NULL,
  `VueOpeVueloNumero` CHAR(4) NULL DEFAULT NULL,
  `VueOpeMatricula` VARCHAR(50) NULL DEFAULT NULL,
  `AerTipKey` INT(11) NULL DEFAULT NULL,
  `AerTipDesignador` CHAR(4) NULL DEFAULT NULL,
  `VueOpeOrigenArpKey` INT(11) NULL DEFAULT NULL,
  `VueOpeAeropuertoOrigen` CHAR(4) NULL DEFAULT NULL,
  `VueOpeDestinoArpKey` INT(11) NULL DEFAULT NULL,
  `VueOpeAeropuertoDestino` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFecha` DATE NULL DEFAULT NULL,
  `VueOpeFechaSalidaPlan` DATE NULL DEFAULT NULL,
  `VueOpeHoraSalidaPlan` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaSalidaReal` DATE NULL DEFAULT NULL,
  `VueOpeHoraSalidaReal` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaLlegadaPlan` DATE NULL DEFAULT NULL,
  `VueOpeHoraLlegadaPlan` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaLlegadaReal` DATE NULL DEFAULT NULL,
  `VueOpeHoraLlegadaReal` CHAR(4) NULL DEFAULT NULL,
  `VueOpeNivel` CHAR(4) NULL DEFAULT NULL,
  `VueOpeTD` TINYINT(4) NULL DEFAULT NULL,
  `VueOpeLP` TINYINT(4) NULL DEFAULT NULL,
  `VueOpeUsuarioC` CHAR(20) NULL DEFAULT NULL,
  `VueOpeFechaC` DATE NULL DEFAULT NULL,
  `VueOpeFechaHoraC` DATETIME NULL DEFAULT NULL,
  `VueOpeAeropuertoC` CHAR(4) NULL DEFAULT NULL,
  `VueOpeUsuarioM` CHAR(20) NULL DEFAULT NULL,
  `VueOpeFechaM` DATE NULL DEFAULT NULL,
  `VueOpeFechaHoraM` DATETIME NULL DEFAULT NULL,
  `VueOpeAeropuertoM` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueFchKey` INT(11) NULL DEFAULT NULL,
  `VueBIOperacionDEP` TINYINT(4) NULL DEFAULT NULL,
  `VueBIOperacionARR` TINYINT(4) NULL DEFAULT NULL,
  `VueBIValidacionItinerarioDEP` TINYINT(4) NULL DEFAULT NULL,
  `VueBIValidacionItinerarioARR` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`VueOpeKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 30587
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`vuelooperacionmod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`vuelooperacionmod` (
  `VueOpeModKey` INT(11) NOT NULL AUTO_INCREMENT,
  `VueOpeKey` INT(11) NOT NULL,
  `VueTipKey` INT(11) NULL DEFAULT NULL,
  `VueTipDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `VueCatKey` INT(11) NULL DEFAULT NULL,
  `VueCatDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `OpeDsgKey` INT(11) NULL DEFAULT NULL,
  `OpeKey` INT(11) NULL DEFAULT NULL,
  `OpeDescripcion` VARCHAR(100) NULL DEFAULT NULL,
  `OpeDsgDesignadorOACI` CHAR(10) NULL DEFAULT NULL,
  `VueOpeVueloNumero` CHAR(4) NULL DEFAULT NULL,
  `VueOpeMatricula` VARCHAR(50) NULL DEFAULT NULL,
  `AerTipKey` INT(11) NULL DEFAULT NULL,
  `AerTipDesignador` CHAR(4) NULL DEFAULT NULL,
  `VueOpeOrigenArpKey` INT(11) NULL DEFAULT NULL,
  `VueOpeAeropuertoOrigen` CHAR(4) NULL DEFAULT NULL,
  `VueOpeDestinoArpKey` INT(11) NULL DEFAULT NULL,
  `VueOpeAeropuertoDestino` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFecha` DATE NULL DEFAULT NULL,
  `VueOpeFechaSalidaPlan` DATE NULL DEFAULT NULL,
  `VueOpeHoraSalidaPlan` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaSalidaReal` DATE NULL DEFAULT NULL,
  `VueOpeHoraSalidaReal` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaLlegadaPlan` DATE NULL DEFAULT NULL,
  `VueOpeHoraLlegadaPlan` CHAR(4) NULL DEFAULT NULL,
  `VueOpeFechaLlegadaReal` DATE NULL DEFAULT NULL,
  `VueOpeHoraLlegadaReal` CHAR(4) NULL DEFAULT NULL,
  `VueOpeNivel` CHAR(4) NULL DEFAULT NULL,
  `VueOpeTD` TINYINT(4) NULL DEFAULT NULL,
  `VueOpeLP` TINYINT(4) NULL DEFAULT NULL,
  `VueOpeUsuarioC` CHAR(20) NULL DEFAULT NULL,
  `VueOpeFechaC` DATE NULL DEFAULT NULL,
  `VueOpeFechaHoraC` DATETIME NULL DEFAULT NULL,
  `VueOpeAeropuertoC` CHAR(4) NULL DEFAULT NULL,
  `VueOpeUsuarioM` CHAR(20) NULL DEFAULT NULL,
  `VueOpeFechaM` DATE NULL DEFAULT NULL,
  `VueOpeFechaHoraM` DATETIME NULL DEFAULT NULL,
  `VueOpeAeropuertoM` CHAR(4) NULL DEFAULT NULL,
  `ItiAutVueFchKey` INT(11) NULL DEFAULT NULL,
  `VueOpeModBitacoraCambios` TEXT NULL DEFAULT NULL,
  `VueOpeModFecha` DATE NULL DEFAULT NULL,
  `VueOpeModFechaHora` DATETIME NULL DEFAULT NULL,
  `VueOpeModUsuario` CHAR(20) NULL DEFAULT NULL,
  `VueOpeModAeropuerto` CHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`VueOpeModKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 183
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ahac`.`vuelotipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ahac`.`vuelotipo` (
  `VueTipKey` INT(11) NOT NULL AUTO_INCREMENT,
  `VueTipDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `VueTipCodigo` VARCHAR(5) NULL DEFAULT NULL,
  `VueTipEstatus` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`VueTipKey`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

USE `bd_autoscraping` ;

-- -----------------------------------------------------
-- function buscar_asignatura
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_asignatura`(`_cod_asignatura` VARCHAR(8), `_txt_nombre_asignatura` VARCHAR(100)) RETURNS int(11)
begin 
	declare resultado int;
	declare cod_asignatura varchar(8);

select cod_asignatura_pk into cod_asignatura 
		from tbl_asignatura
		where cod_asignatura_pk = _cod_asignatura;

		if cod_asignatura = _cod_asignatura
		then
			set resultado = 1;
        else
			set resultado = 0;
		insert into tbl_asignatura (cod_asignatura_pk, txt_nombre_asignatura) values (_cod_asignatura, _txt_nombre_asignatura);
        end if;
        
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_carga
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_carga`(`_num_seccion` INT, `_num_periodo` INT, `_num_anio` INT, `_cod_asignatura` VARCHAR(8), `_txt_HI` VARCHAR(6), `_txt_HF` VARCHAR(6), `_txt_dias` VARCHAR(15), `_txt_aula` VARCHAR(200), `_txt_edificio` VARCHAR(10), `_num_docente` VARCHAR(30)) RETURNS int(11)
begin 
declare resultado int;
declare num_seccion, num_periodo, num_anio int;
declare cod_asignatura varchar (8);

declare num_docente varchar (30);
declare txt_HI_, txt_HF_ varchar(6);
declare txt_dias_ varchar (15);
declare txt_aula_ varchar (200);
declare txt_edificio_ varchar (20);


select num_seccion_pk, num_periodo_pk, num_anio_pk, cod_asignatura_ck, num_docente_ck, txt_HI, txt_HF, txt_dias, txt_aula, txt_edificio
into num_seccion, num_periodo, num_anio, cod_asignatura, num_docente, txt_HI_, txt_HF_, txt_dias_, txt_aula_, txt_edificio_
from tbl_seccion
where num_seccion_pk = _num_seccion and
	  num_periodo_pk = _num_periodo and
      num_anio_pk = _num_anio and
      cod_asignatura_ck = _cod_asignatura;

if num_seccion = _num_seccion and 
   num_periodo = _num_periodo and
   num_anio = _num_anio and
   cod_asignatura = _cod_asignatura
then
	set resultado = 1;
	if  num_docente <> _num_docente or num_docente is null then
		
		update tbl_seccion
		set num_docente_ck = _num_docente
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;

	if  txt_HI_ <> _txt_HI or txt_HI_ is null then
		
		update tbl_seccion
		set txt_HI = _txt_HI
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;

	if  txt_HF_ <> _txt_HF or txt_HF_ is null then 
		
		update tbl_seccion
		set txt_HF = _txt_HF
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;

	if  txt_dias_ <> txt_dias_ or txt_dias_ is null then
		
		update tbl_seccion
		set txt_dias = _txt_dias
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;

	if  txt_aula_ <> _txt_aula or txt_aula_ is null then 
	
		update tbl_seccion
		set txt_aula = _txt_aula
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;

	if  txt_edificio_ <> _txt_edificio or txt_edificio_ is null then 
		
		update tbl_seccion
		set txt_edificio = _txt_edificio
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
		
	end if;
	
	if num_docente <> _num_docente or num_docente is null then
		
		update tbl_seccion
		set num_docente_ck = _num_docente
		where num_seccion_pk = _num_seccion and num_periodo_pk = _num_periodo and num_anio_pk = _num_anio and cod_asignatura_ck = _cod_asignatura;
	
	end if;
	
else
	set resultado = 0;
	
end if;
            
return resultado;

end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_docente
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_docente`(`_num_docente` VARCHAR(30), `_nombre_docente` VARCHAR(60)) RETURNS int(11)
begin 
declare resultado int;
declare num_docente varchar(20);

select num_docente_pk into num_docente 
from tbl_docente
where num_docente_pk = _num_docente;

if num_docente = _num_docente
then
	set resultado = 1;
else
	set resultado = 0;
insert into tbl_docente (num_docente_pk, txt_nombre) values (_num_docente, _nombre_docente);
end if;
            
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_estudiante
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_estudiante`(`_num_cuenta` VARCHAR(20), `_nombre_alumno` VARCHAR(100), `_txt_centro_estudio` VARCHAR(100), `_txt_carrera` VARCHAR(100)) RETURNS int(11)
begin 
	declare resultado int;
	declare num_cuenta varchar(20);

select num_cuenta_pk into num_cuenta 
from tbl_estudiante
where num_cuenta_pk = _num_cuenta;

if num_cuenta = _num_cuenta
then
	set resultado = 1;
else
	set resultado = 0;
insert into tbl_estudiante (num_cuenta_pk, txt_nombre, txt_centro_estudio, txt_carrera) values (_num_cuenta, _nombre_alumno, _txt_centro_estudio, _txt_carrera);
end if;
            
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_historial
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_historial`(`_num_cuenta` VARCHAR(20), `_num_seccion` INT, `_num_periodo` INT, `_num_anio` INT, `_cod_asignatura` VARCHAR(8), `_num_calificacion` INT, `_num_uv` INT, `_txt_obs` VARCHAR(20)) RETURNS int(11)
begin 
	declare resultado int;
	declare num_seccion, num_periodo, num_anio int;
	declare cod_asignatura varchar (8);
	declare num_cuenta varchar(20);

select num_cuenta_ck, cod_asignatura_ck, num_seccion_pk, num_periodo_pk, num_anio_pk
into num_cuenta, cod_asignatura, num_seccion, num_periodo, num_anio
from tbl_historial
where num_cuenta_ck = _num_cuenta and
	  cod_asignatura_ck = _cod_asignatura and 
	  num_seccion_pk = _num_seccion and
	  num_periodo_pk = _num_periodo and
      num_anio_pk = _num_anio;
      

if num_cuenta = _num_cuenta and
   cod_asignatura = _cod_asignatura and
   num_seccion = _num_seccion and 
   num_periodo = _num_periodo and
   num_anio = _num_anio
   
then
	set resultado = 1;
else
	set resultado = 0;
	if _num_uv = 0
	THEN
		insert into tbl_historial (num_cuenta_ck, cod_asignatura_ck, num_seccion_pk, num_periodo_pk, num_anio_pk, num_calificacion, num_uv, txt_obs) 
						values (_num_cuenta, _cod_asignatura, _num_seccion, _num_periodo, _num_anio, _num_calificacion, 4, _txt_obs);
	else
		insert into tbl_historial (num_cuenta_ck, cod_asignatura_ck, num_seccion_pk, num_periodo_pk, num_anio_pk, num_calificacion, num_uv, txt_obs) 
						values (_num_cuenta, _cod_asignatura, _num_seccion, _num_periodo, _num_anio, _num_calificacion, _num_uv, _txt_obs);
	end if;
end if;
            
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_periodo
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_periodo`(`_num_periodo` INT, `_num_anio` INT) RETURNS int(11)
begin 
	declare resultado int;
	declare num_periodo2, num_anio2 int;

select num_periodo_pk, num_anio_pk into num_periodo2, num_anio2 
		from tbl_periodo
		where num_periodo_pk = _num_periodo and num_anio_pk = _num_anio;

		if num_periodo2 = _num_periodo and num_anio2 = _num_anio
		then
			set resultado = 1;
        else
			set resultado = 0;
			insert into tbl_periodo (num_periodo_pk, num_anio_pk) values(_num_periodo, _num_anio);
        end if;
        
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- function buscar_seccion
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `buscar_seccion`(`_num_seccion` INT, `_num_periodo` INT, `_num_anio` INT, `_cod_asignatura` VARCHAR(8)) RETURNS int(11)
begin 
	declare resultado int;
	declare num_seccion, num_periodo, num_anio int;
	declare cod_asignatura varchar (8);

select num_seccion_pk, num_periodo_pk, num_anio_pk, cod_asignatura_ck 
into num_seccion, num_periodo, num_anio, cod_asignatura
from tbl_seccion
where num_seccion_pk = _num_seccion and
	  num_periodo_pk = _num_periodo and
      num_anio_pk = _num_anio and
      cod_asignatura_ck = _cod_asignatura;


if num_seccion = _num_seccion and 
   num_periodo = _num_periodo and
   num_anio = _num_anio and
   cod_asignatura = _cod_asignatura
then
	set resultado = 1;
else
	set resultado = 0;
	if _num_seccion = 0
	then
        insert into tbl_seccion (num_periodo_pk, 		num_anio_pk, cod_asignatura_ck) values (_num_periodo, _num_anio, _cod_asignatura);
        SELECT (SELECT `AUTO_INCREMENT`
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'bd_autoscraping'
AND   TABLE_NAME   = 'tbl_seccion')-1 INTO resultado;
	else 
            insert into tbl_seccion (num_seccion_pk, num_periodo_pk, 		num_anio_pk, cod_asignatura_ck) values (_num_seccion, _num_periodo, _num_anio, _cod_asignatura);
            set resultado = 1;

    end if;
end if;          
return resultado;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_carga
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertar_carga`(IN `_cod_asignatura` VARCHAR(8), IN `_txt_nombre_asignatura` VARCHAR(200), IN `_num_seccion` INT, IN `_num_periodo` INT, IN `_num_anio` INT, IN `_txt_HI` VARCHAR(6), IN `_txt_HF` VARCHAR(6), IN `_txt_dias` VARCHAR(15), IN `_txt_aula` VARCHAR(200), IN `_txt_edificio` VARCHAR(10), IN `_num_docente` VARCHAR(30), IN `_txt_nombre_docente` VARCHAR(60))
begin 

declare respuesta_periodo int; 
declare respuesta_asignatura int; 
declare respuesta_carga int; 
declare respuesta_docente int; 
declare respuesta_seccion int; 

set respuesta_periodo = buscar_periodo(_num_periodo, _num_anio);

set respuesta_asignatura = buscar_asignatura(_cod_asignatura, _txt_nombre_asignatura);

set respuesta_docente = buscar_docente(_num_docente, _txt_nombre_docente);

set respuesta_seccion = buscar_seccion(_num_seccion, _num_periodo, _num_anio, _cod_asignatura);

set respuesta_carga = buscar_carga(_num_seccion, _num_periodo, _num_anio, _cod_asignatura, 
_txt_HI, _txt_HF, _txt_dias, _txt_aula, _txt_edificio, _num_docente);

end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_historial
-- -----------------------------------------------------

DELIMITER $$
USE `bd_autoscraping`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertar_historial`(IN `_num_cuenta` VARCHAR(20), IN `_txt_nombre_alumno` VARCHAR(100), IN `_cod_asignatura` VARCHAR(8), IN `_txt_nombre_asignatura` VARCHAR(200), IN `_num_seccion` INT, IN `_num_periodo` INT, IN `_num_anio` INT, IN `_num_calificacion` INT, IN `_num_uv` INT, IN `_txt_obs` VARCHAR(20), IN `_txt_centro_estudio` VARCHAR(100), IN `_txt_carrera` VARCHAR(100))
begin 

	declare respuesta_periodo int; 
	declare respuesta_asignatura int; 
	declare respuesta_estudiante int;
	declare respuesta_seccion int; 
	declare respuesta_historial int;

set respuesta_periodo = buscar_periodo(_num_periodo, _num_anio);

set respuesta_asignatura = buscar_asignatura(_cod_asignatura, _txt_nombre_asignatura);

set respuesta_estudiante = buscar_estudiante(_num_cuenta, _txt_nombre_alumno, _txt_centro_estudio, _txt_carrera);

set respuesta_seccion = buscar_seccion(_num_seccion, _num_periodo, _num_anio, _cod_asignatura);

if respuesta_seccion != 1
THEN
	set respuesta_historial = buscar_historial (_num_cuenta, respuesta_seccion, _num_periodo, _num_anio, _cod_asignatura, _num_calificacion, _num_uv, _txt_obs);
else
    set respuesta_historial = buscar_historial (_num_cuenta, _num_seccion, _num_periodo, _num_anio, _cod_asignatura, _num_calificacion, _num_uv, _txt_obs);
end if;
end$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
